### ISSUE TITLE
Support for Blazor WASM

### ISSUE THREAD

**Issue by vitalybrandes** [logto-io/csharp#13]
Having support for Blazor WASM will be nice.

**Comment by kjbtech** [comment]
Using Blazor WASM should lead us to use Backend For Frontend (as we can see here with [IdentityServer](https://github.com/DuendeSoftware/BFF).
Don't you think ?

**Comment by vitalybrandes** [comment]
It's depend.
I am running microfrontend on containers that have multiple "backends"..

**Comment by kjbtech** [comment]
@vitalybrandes The link that you provided in the other issue (https://github.com/WildGums/Blorc.OpenIdConnect) could help on that?

Maybe we can contribute to the SDK?
Is it possible @gao-sun?

**Comment by gao-sun** [comment]
@kjbtech yes i just contributed some code and add the sample in #17
