### ISSUE TITLE
feature request: Provide a sample example when using BFF concept 

### ISSUE THREAD

**Issue by kjbtech** [logto-io/csharp#14]
### What problem did you meet?
When using Authentication and Authorization, we face some security concerns.
In that matters, we could offer the possibility to implement BFF concept wit logto.io.

Some sources that advocate general advantages and drawbacks:

- [Duende software](https://docs.duendesoftware.com/identityserver/v5/bff/overview/)
- https://blog.bitsrc.io/bff-pattern-backend-for-frontend-an-introduction-e4fa965128bf
- https://medium.com/mobilepeople/backend-for-frontend-pattern-why-you-need-to-know-it-46f94ce420b0

### Describe what you'd like Logto to have
ASP NET Core Blazor WASM instance example with a server app as BFF to secure authentication and avoid direct call from front-end to logto server.
That means:
- 1 ASP Net Blazor WASM project
- 1 ASP Net API as the backend/proxy
- 1 ASP Net Web API (to show implementation example)

The main purpose of this issue is to record potential need, we should see it a bonus.

Personal notes:
I'm working on in on my side so I should be able to show a working example in a few weeks. 
So I will be happy to contribute and share my experience.

**Comment by vitalybrandes** [comment]
Regarding the wasm, sudgest you to check https://github.com/WildGums/Blorc.OpenIdConnect

**Comment by wangsijie** [comment]
Could you take a look on this @gao-sun? Thanks

**Comment by vitalybrandes** [comment]
He already did ☺️.

**Comment by kjbtech** [comment]
Hi @vitalybrandes ,
I do not understand how the example that you provided is a OpenIdConnect implementation of BFF concept.
It's more a Blazor WASM implementation to call an authentication server that use OpenIdConnect?
Could you enlightened me?

**Comment by gao-sun** [comment]
@kjbtech I'm working on this, will update here once it's completed

**Comment by gao-sun** [comment]
@kjbtech Please let me know if the new [blazor sample](https://github.com/logto-io/csharp/tree/master/samples/sample-blazor) works for you. (assume your BFF is using blazor + razor pages)
